### ISSUE TITLE
Many comment style, more mistakes

### ISSUE THREAD

**Issue by HanzCEO** [netspooky/xx#4]
When I see the README content regarding comment line specification, it is just redundant to have all of the comment style. Especially the box ascii style.

What if my magic byte is an ascii box art? Uncommon but a possibility.

**Comment by netspooky** [comment]
Hi there,
The reason there are so many comment styles and hex formats supported is to make it easier to work with lots of different styles people have. The box drawing characters are included so that people can create diagrams to illustrate the hex.

The format itself is meant for people who want to use text to annotate data, or to just have a scratchpad in hex that they can use for whatever they like.

As for the comments being interpreted as data, you can just turn it into a hex byte. Like instead of writing `#` just write `23`.

Does that answer your question?

**Comment by HanzCEO** [comment]
Hmm, that's sufficient. Thank you
